name: work
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4=py313hca03da5_0
  - aiohttp=3.11.10=py313h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - arrow-cpp=19.0.0=h0b7d223_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py313hca03da5_0
  - aws-c-auth=0.6.19=h80987f9_0
  - aws-c-cal=0.5.20=h80987f9_0
  - aws-c-common=0.8.5=h80987f9_0
  - aws-c-compression=0.2.16=h80987f9_0
  - aws-c-event-stream=0.2.15=h313beb8_0
  - aws-c-http=0.6.25=h80987f9_0
  - aws-c-io=0.13.10=h80987f9_0
  - aws-c-mqtt=0.7.13=h80987f9_0
  - aws-c-s3=0.1.51=h80987f9_0
  - aws-c-sdkutils=0.1.6=h80987f9_0
  - aws-checksums=0.1.13=h80987f9_0
  - aws-crt-cpp=0.18.16=h313beb8_0
  - aws-sdk-cpp=1.11.212=hdd7fb2f_0
  - blas=1.0=openblas
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.4.2=py313ha35b7ea_0
  - brotli-python=1.0.9=py313h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=py313hca03da5_0
  - comm=0.2.2=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h9131b1a_1
  - datasets=3.3.2=py313hca03da5_0
  - debugpy=1.8.11=py313h313beb8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.13=py313hca03da5_0
  - dill=0.3.8=py313hca03da5_0
  - et_xmlfile=1.1.0=py313hca03da5_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py313hca03da5_0
  - frozenlist=1.5.0=py313h80987f9_0
  - fsspec=2024.12.0=py313hca03da5_0
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py313h5c1b81f_0
  - greenlet=3.1.1=py313h313beb8_0
  - huggingface_hub=0.29.2=py313hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py313hca03da5_0
  - importlib-metadata=8.5.0=py313hca03da5_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py313hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.20.1=hf3e1bf2_1
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.12.1=hde089ae_0
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - liblzma=5.6.4=h39f12f2_0
  - liblzma-devel=5.6.4=h39f12f2_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.29=hea593b9_0
  - libpq=17.4=h02f6b3c_0
  - libprotobuf=5.29.3=h9f9f828_0
  - libre2-11=2024.07.02=h313beb8_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.15.0=h73c2103_2
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py313hca03da5_0
  - multidict=6.1.0=py313h80987f9_0
  - multiprocess=0.70.15=py313hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py313hca03da5_0
  - nomkl=3.0=0
  - numexpr=2.10.1=py313h5d9532f_0
  - numpy=2.2.5=py313hdcf7240_0
  - numpy-base=2.2.5=py313h9d8309b_0
  - openldap=2.6.4=he7ef289_0
  - openpyxl=3.1.5=py313h80987f9_1
  - openssl=3.5.0=h81ee809_1
  - opentelemetry-api=1.30.0=py313hca03da5_0
  - orc=2.1.1=h55d209b_0
  - packaging=24.2=py313hca03da5_0
  - pandas=2.2.3=py313hcf29cfe_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py313h80987f9_0
  - protobuf=5.29.3=py313h514c7bf_0
  - psutil=7.0.0=py313h90d716c_0
  - psycopg2=2.9.10=py313h80987f9_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py4j=0.10.9.2=pyhd3eb1b0_0
  - pyarrow=19.0.0=py313h313beb8_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py313hca03da5_0
  - pyspark=3.1.2=pyhd3eb1b0_0
  - python=3.13.2=h4862095_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h80987f9_0
  - python_abi=3.13=0_cp313
  - pytorch=2.5.1=gpu_mps_py313hbd1d365_204
  - pyyaml=6.0.2=py313h80987f9_0
  - pyzmq=26.2.0=py313h313beb8_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.2=h1a28f6b_0
  - regex=2024.11.6=py313h80987f9_0
  - requests=2.32.3=py313hca03da5_1
  - safetensors=0.5.3=py313h00184e3_0
  - setuptools=72.1.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - snappy=1.2.1=h313beb8_0
  - sqlalchemy=2.0.39=py313hbe2cdee_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py313hca03da5_1
  - tk=8.6.14=h6ba3021_0
  - tokenizers=0.21.0=py313h5b23da0_0
  - tornado=6.5=py313h90d716c_0
  - tqdm=4.67.1=py313h7eb115d_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.49.0=py313hca03da5_0
  - typing-extensions=4.12.2=py313hca03da5_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.3.0=py313hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py313hca03da5_0
  - wrapt=1.17.0=py313h80987f9_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.6.4=h9a6d368_0
  - xz-gpl-tools=5.6.4=h9a6d368_0
  - xz-tools=5.6.4=h39f12f2_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.18.0=py313h80987f9_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py313hca03da5_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hfb09047_0
  - pip:
      - accelerate==1.6.0
      - airportsdata==20250523
      - annotated-types==0.7.0
      - anyio==4.9.0
      - babel==2.17.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - courlan==1.3.2
      - dateparser==1.2.1
      - diskcache==5.6.3
      - duckduckgo-search==8.0.2
      - genson==1.3.0
      - h11==0.16.0
      - htmldate==1.9.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-ws==0.7.2
      - interegular==0.3.3
      - joblib==1.5.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - justext==3.0.2
      - lark==1.2.2
      - lmstudio==1.3.1
      - lxml==5.4.0
      - lxml-html-clean==0.4.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - msgspec==0.19.0
      - ollama==0.4.8
      - outlines-core==0.1.26
      - peft==0.15.2
      - primp==0.15.0
      - pycountry==24.6.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pytz==2025.2
      - referencing==0.36.2
      - rich==14.0.0
      - rpds-py==0.25.1
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sniffio==1.3.1
      - threadpoolctl==3.6.0
      - tld==0.13.1
      - trafilatura==2.0.0
      - trl==0.17.0
      - typing-inspection==0.4.1
      - tzlocal==5.3.1
      - wsproto==1.2.0
prefix: /Users/alhu/miniconda3/envs/work
